name: Build BlanketOps Environments CLI
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install Mage
        run: go install github.com/magefile/mage@latest

      - name: Build CLI (Dynamic)
        run: mage build

      - name: Upload CLI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: blanketops-environments
          path: bin/blanketops-environments-cli
          retention-days: 14

  static-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install Mage
        run: go install github.com/magefile/mage@latest

      - name: Build Static Binaries (AMD64 & ARM64)
        run: |
          mage static
          mage staticarm64

      - name: Upload Static Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: blanketops-environments-cli-static
          path: bin/blanketops-environments-cli-static*
          retention-days: 14
